### ISSUE TITLE
Can't run ModLoader mods alongside compiled mod

### ISSUE THREAD

**Issue by CyborgCabbage** [MCPHackers/RetroMCP-Java#40]
So I combine ModLoader, forge, and the mod I want to edit into "minecraft.jar" in the jars folder and (after fixing decompilation errors) everything works. The issue comes in when I add HowManyItems to "jars/mods" to help test the mod.
[crash.txt](https://github.com/MCPHackers/RetroMCP-Java/files/10831103/crash.txt)

**Comment by Lassebq** [comment]
Are you running with java 8? Also, RMCP runs deobfuscated mod by default. Check "Run build" parameter in launching options

**Comment by Lassebq** [comment]
You also have to build it first in order to run build

**Comment by CyborgCabbage** [comment]
Yes I am on Java 8. I have tried with obfuscation on and off. The mod I am developing builds just fine it's just when mod loader tries to load a mod from the mods folder instead of inside the jar that it crashes.

**Comment by Lassebq** [comment]
No, that's not what I'm saying. there's "Run build" option, use that. Obfuscation is just making mod classes obfuscated (in build)
![image](https://user-images.githubusercontent.com/68742864/221357396-4f2ffdae-3352-4e76-884b-b5d98190eccd.png)
Although this is a screenshot from a newer version, there's still an option like that. Enable it, then use context menu to launch client

**Comment by Lassebq** [comment]
Don't forget to run build task, as I said

**Comment by CyborgCabbage** [comment]
Yes I have tried with run build enabled and disabled, it has not effect on the error. I am also running the build task.

**Comment by Lassebq** [comment]
Would be helpful if you could provide info as to where and when it crashes and with what error

**Comment by CyborgCabbage** [comment]
I literally linked the crash text

**Comment by Lassebq** [comment]
Wait, I'm confused *what is your mod?* Is it HMI mod? or are you adding that separately alongside your mod? Do you have HMI deobfuscated? decompiled?

**Comment by CyborgCabbage** [comment]
No HMI is not the mod I am developing, I just want to run the game with it to make it easier to test my mod. I am adding HMI to the "jars/mods" folder so that mod loader can load it, but this does not work (resulting in error you see). Because of this issue I have always had to put the built mod into Prism to test it properly, but now I have a issue that is really difficult to debug without debugging tools so I would like to be able to load external mods from RetroMCP.

**Comment by Lassebq** [comment]
I see, apparently there was an issue with running build. It'll be fixed in the next release

**Comment by Lassebq** [comment]
Is this still an issue? Or does it work in v1.0?

**Comment by CyborgCabbage** [comment]
Still doesn't work, I did a bunch of debugging and I think the issue is that the deobfuscated.jar puts everything in net/minecraft/src whereas when you run the game they are all the root. I tried modifying launch wrapper to try a path with/without net.minecraft.src. when it can't find the class file but it didn't work, it freaks out because the Binary name in the file doesn't match the path (or something like that). I pushed the changes I made to a fork of LaunchWrapper so you can see what I am talking about (even though it didn't fix issue).

**Comment by PhoenixVX** [comment]
Can you provide a bit more information on the intended functionality of this?

Are you trying to run ML mods alongside a compiled (not reobfuscated) mod?
If that's the case, this isn't intended to work. If it's something else, please say so.

**Comment by PhoenixVX** [comment]
Closing issue as inactive.
Please reopen if the issue persists and is still in scope for RetroMCP-Java.
